site: iot.com.hr
title: Internet stvari (IOT) uradi sam
greetings: Hola, konnichiwa, bonjour... 👋
description: IOT svijet oko nas
  
lang: en-US
timezone:  Europe/Rome
repo: https://github.com/doxikus/doxikus.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: powex # replace with your disqus shortname

author:
  name: doxikus
  bio: Software engineer, tech enthusiast, permaculturist...
  userpicture: 
  username: # general username
  github: doxikus # github username
  twitter: doxikus # twitter username
  email: stanislav.mihic@gmail.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://doxikus.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
url: "http://localhost:4000" # 
baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

paginate: 5


